### ISSUE TITLE
Make io functions accept file like objects

### ISSUE THREAD

**Issue by rwl** [cuihantao/andes#107]
**Is your feature request related to a problem? Please describe.**
Currently, if I have data in memory that I wish to parse into a `System` it has to be written out to a temporary file and the path passed to a `read` function from an `io` module.

**Describe the solution you'd like**
It would be good if the `io` modules had `read_file` functions that would accept file-like objects (e.g. `StringIO`). These could be called from the existing `read` functions that would still take paths and handle opening/closing files.

**Describe alternatives you've considered**
The `xlsx` [module](https://github.com/cuihantao/andes/blob/3da707a78a9a97326973f90ed68a28e311327851/andes/io/xlsx.py#L105) already supports this as the Pandas `ExcelFile` [constructor](https://github.com/pandas-dev/pandas/blob/v0.12.0/pandas/io/excel.py#L61) accepts file-like objects. The `json` module is simple enough to just copy, but the `matpower` and `psse` modules call `open`.

**Comment by cuihantao** [comment]
Typed on phone, please excuse the formatting. 

I will work on refactoring the parsers. 

For the xlsx reader, I have to switch back to pandas.read_excel to specify openpyxl as the engine, since xlrd deprecated the support for xlsx file. But that shouldn’t make a difference for the purpose of reading from a file object.

**Comment by cuihantao** [comment]
Fixed it in dfeea9.

Added a wrapper `read_file_like(infile)` in `andes.io.__init__` to accept a file-like or a str for path.
Modified each parser to use it instead of directly calling `open`.

To create a system object and load from file, use

```
import andes

fd = open(andes.get_case("npcc/npcc.raw"))

ss = andes.System()  # args can go here.
andes.io.psse.read(ss, fd)
```

In order for Andes to output correctly, you will need to call `ss.files.set("presumed_case_name")` manually. I hope you won't mind checking the code in `andes/variables/fileman.py`.

Let me know if you have other suggestions.

**Comment by rwl** [comment]
Thank you very much for making these changes so quickly. This will be much more convenient than writing out to temporary files.

**Comment by cuihantao** [comment]
You are welcome. As always, thank you for the suggestion.
