### ISSUE TITLE
LCC-MMC HVDC/MTDC system

### ISSUE THREAD

**Issue by YaeSakura1** [cuihantao/andes#130]
If I need to use ANDES to implement LCC-MMC three-terminal or multi-terminal HVDC transmission system, is it possible? What models and parameters do I need to add?
To simulate the switching in MMC, i need an electromagnetic simulation tool ,like PSCAD?
Is there a model of LCC or MMC in ANDES?I need to program LCC and MMC models, right?
Thank you for your guidance！

**Comment by cuihantao** [comment]
You will need to use PSCAD or EMTDC. I don't think ANDES can currently support simulating down to the switching level.

**Comment by YaeSakura1** [comment]
Does ANDES have an existing LCC model?

**Comment by cuihantao** [comment]
@YaeSakura1: Andes does not have an LCC model yet. You might be able to program the LCC model in Milano's book (Power System Modelling and Scripting) following the modeling examples.

**Comment by YaeSakura1** [comment]
I want to use ANDES to implement the AC/DC power flow problem of the LCC-VSC hybrid system, and then study the electromechanical transient.Don't need to simulating down to the switching level.

**Comment by cuihantao** [comment]
Hi @YaeSakura1 ,

I saw your work in progress about the LCC-VSC models in power flow. It seems to be in the right direction. Keep adding the equations, and you should be good to go.

One practice I noticed in your fork is that you changed default arguments or config values in the program. It is totally fine because it's your fork. Just want to remind you that these default arguments are "fallback", and you can always supply with your custom ones when calling, without having to change the code.

**Comment by YaeSakura1** [comment]
Hi @cuihantao ,
Thank you for your advice.
What other variables and equations should I add?
And how do I call my newly added model?

Please tell me how I can provide custom parameters at call time without having to change the code.
Thank you

**Comment by cuihantao** [comment]
Please refer to the documentation for adding new models. Specifically, you can go through `Model Cookbook` and read the code.

I will close the issue for now. If you have more specific ideas to discuss, please post it to `Discussions`.
